import { query } from "./client.js";

const JOB_STATUSES = new Set(["queued", "running", "completed", "failed", "partially_completed"]);
const BATCH_STATUSES = new Set(["queued", "running", "completed", "failed"]);

export async function createQuarterlyJob({ memberId, urlListId, propertyUrl, searchType = "web", quarter }) {
  const previous = quarter.previous || quarter.previousRange;
  const current = quarter.current || quarter.currentRange || quarter;
  const r = await query(`insert into team_quarterly_jobs (member_id,url_list_id,property_url,search_type,quarter_label,current_start,current_end,previous_start,previous_end,status,strategy)
    values ($1,$2,$3,$4,$5,$6,$7,$8,$9,'queued','batch_50') returning *`, [memberId, urlListId, propertyUrl, searchType, current.label || quarter.label, current.start, current.end, previous.start, previous.end]);
  return r.rows[0];
}
export async function createQuarterlyJobBatches({ jobId, urls, batchSize = 50 }) {
  const values = [];
  for (let i=0;i<urls.length;i+=batchSize) values.push({ batchIndex: values.length, startIndex: i, endIndex: Math.min(i+batchSize, urls.length)-1, urlCount: Math.min(batchSize, urls.length-i) });
  for (const b of values) await query(`insert into team_quarterly_job_batches (job_id,batch_index,start_index,end_index,url_count) values ($1,$2,$3,$4,$5)`, [jobId,b.batchIndex,b.startIndex,b.endIndex,b.urlCount]);
  await query(`update team_quarterly_jobs set total_urls=$2,total_batches=$3,progress=case when $2=0 then 100 else 0 end where id=$1`, [jobId, urls.length, values.length]);
  return values;
}
export async function getQuarterlyJob(jobId) { const r = await query(`select j.*,m.name member_name,m.email member_email,l.urls_json from team_quarterly_jobs j left join team_members m on m.id=j.member_id left join team_member_url_lists l on l.id=j.url_list_id where j.id=$1`, [jobId]); return r.rows[0] || null; }
export async function listQuarterlyJobs(filters={}) { const params=[]; let where=""; if (filters.memberId) { params.push(filters.memberId); where=`where j.member_id=$${params.length}`; } const r=await query(`select j.*,m.name member_name from team_quarterly_jobs j left join team_members m on m.id=j.member_id ${where} order by j.created_at desc limit 50`, params); return r.rows; }
export async function updateQuarterlyJobProgress(jobId, fields={}) { if (fields.status && !JOB_STATUSES.has(fields.status)) throw new Error("Invalid job status."); const allowed=["status","total_urls","total_batches","completed_batches","processed_urls","progress","warnings","error_message","completed_at"]; const sets=[]; const params=[jobId]; for (const k of allowed) if (Object.prototype.hasOwnProperty.call(fields,k)) { params.push(k==="warnings"?JSON.stringify(fields[k]):fields[k]); sets.push(`${k}=$${params.length}${k==="warnings"?"::jsonb":""}`); } if(!sets.length) return getQuarterlyJob(jobId); const r=await query(`update team_quarterly_jobs set ${sets.join(",")} where id=$1 returning *`, params); return r.rows[0]; }
export async function getNextQueuedBatch(jobId) { const r=await query(`select * from team_quarterly_job_batches where job_id=$1 and status='queued' order by batch_index limit 1`, [jobId]); return r.rows[0] || null; }
export async function updateBatchStatus(batchId, status, fields={}) { if(!BATCH_STATUSES.has(status)) throw new Error("Invalid batch status."); const r=await query(`update team_quarterly_job_batches set status=$2,error_message=$3,completed_at=$4 where id=$1 returning *`, [batchId,status,fields.errorMessage||fields.error_message||null, fields.completedAt||fields.completed_at||null]); return r.rows[0]; }
export async function saveQuarterlyUrlResults({ jobId, batchId, memberId, rows }) { for (const row of rows) await query(`insert into team_quarterly_url_results (job_id,batch_id,member_id,url,previous_clicks,current_clicks,click_delta,click_delta_percent,previous_impressions,current_impressions,impression_delta,impression_delta_percent,previous_ctr,current_ctr,previous_position,current_position,position_delta,match_type_previous,match_type_current,status,insight) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)`, [jobId,batchId,memberId,row.url,row.previous_clicks||0,row.current_clicks||0,row.click_delta||0,row.click_delta_percent,row.previous_impressions||0,row.current_impressions||0,row.impression_delta||0,row.impression_delta_percent,row.previous_ctr,row.current_ctr,row.previous_position,row.current_position,row.position_delta,row.match_type_previous,row.match_type_current,row.status,row.insight]); }
export async function getQuarterlyJobResults(jobId) { const r=await query(`select r.*,m.name member_name,m.email member_email,j.property_url,j.quarter_label from team_quarterly_url_results r left join team_members m on m.id=r.member_id left join team_quarterly_jobs j on j.id=r.job_id where r.job_id=$1 order by r.current_clicks desc,r.url`, [jobId]); return r.rows; }
export async function getTeamQuarterlyDashboardSummary() { const r=await query(`select count(distinct m.id) filter(where m.status='active')::int total_active_members,coalesce(sum(distinct l.url_count) filter(where l.status='active'),0)::int total_managed_urls,(select count(*)::int from team_quarterly_jobs where status='completed') completed_quarterly_jobs,coalesce(sum(r.current_clicks),0)::int total_current_clicks,coalesce(sum(r.current_impressions),0)::int total_current_impressions,count(r.*) filter(where r.status='Growing')::int total_growing_urls,count(r.*) filter(where r.status='Declining')::int total_declining_urls from team_members m left join team_member_url_lists l on l.member_id=m.id left join team_quarterly_url_results r on r.member_id=m.id`); return r.rows[0]; }
